[package]
name = "aboba"
version = "0.1.0"
authors = ["Vladimir <vladdocan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = {git = "https://github.com/gtk-rs/gtk-rs"}
gstreamer = "0.16.7"
anyhow = "1.0.40"
gstreamer-player = "0.16.0"
derive_more = "0.99.5"
timer = "0.2.0"
chrono = "0.4.19"
lazy_static = "1.4.0"
ffmpeg-next = "4.3"